### ISSUE TITLE
Remove unused rb-tree versions 

### ISSUE THREAD

**Issue by masterkidan** [microsoft/ObjectStoreProvider#29]
It looks like the collectable dependency was removed in https://github.com/microsoft/ObjectStoreProvider/commit/21cd0c817f0367b1b92e9e624dfa62a105a00d8c 

I don't see a reason why the rb-tree dep should still be in the project,  please remove it. Exact list of packages to remove:
```
 "@collectable/core": "^5.0.1",
 "@collectable/red-black-tree": "5.0.1",
 ```

**Comment by M1Les** [comment]
Hey Mukundan, it was not removed, the intent here is to keep supporting both tree implementations for a while, at least until we gain more confidence in the b+tree library.
